# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Diary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # UI
  pod 'SnapKit', '~> 5.0.0'

  # pod 'Firebase/Auth'        # Авторизация
  # pod 'Firebase/Firestore'   # База данных
  # pod 'Firebase/Analytics'   # Аналитика
  # pod 'Firebase/Storage'     # Хранение файлов

end
